### ISSUE TITLE
Unable to use purchase or checkout component, adyen throws error

### ISSUE THREAD

**Issue by RButtsCHQ** [Cleeng/mediastore-sdk#319]
We're testing the new gifting functionality using the component library in a bare-bones react site. After I complete the form and hit Pay, I get this trace from Adyen.js:
```
Adyen.js:329 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')
    at _callee3$ (Adyen.js:329:68)
    at tryCatch (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:23)
    at _next (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (asyncToGenerator.js:19:12)
    at Object.onSubmit (Adyen.js:361:37)
```

This only happens when trying to purchase with a credit card; PayPal is unaffected. The issue manifests with both the Purchase and Checkout Component. I am happy to provide any information you may need.

**Comment by RButtsCHQ** [comment]
Here you go!


https://github.com/Cleeng/mediastore-sdk/assets/79609595/7b78842c-7bf3-4f49-af69-9832882472b5

**Comment by m4tewoosh** [comment]
@RButtsCHQ Yesterday I was investigating fix for this and I believe that I found one. It's waiting to be tested and will be released as soon as possible.

**Comment by m4tewoosh** [comment]
Fix released in 5.4.2 version:
https://github.com/Cleeng/mediastore-sdk/releases/tag/5.4.2
